### ISSUE TITLE
AdminActivity

### ISSUE THREAD

**Issue by JSmevog1** [JSmevog1/GhettoYelp#15]
AdminActivity is the main menu that pops up when an admin logs in. There will be four buttons that are available to admins: Create Review, View Reviews, View All Users, and Add/Remove Restaurants.

**Comment by JSmevog1** [comment]
Merged admin activity in the main menu page, but made it to pop up only if the user is an admin.

**Comment by tkakar0451** [comment]
Restructured some code to make the `isAdmin` check happen in `loginUser` and renamed it `showAdminButtons`. This way we don't get a null pointer exception.
