### ISSUE TITLE
Real-Time Updates with LiveData in RestaurantActivity

### ISSUE THREAD

**Issue by YusraAshar** [JSmevog1/GhettoYelp#43]
Integrated LiveData in RestaurantViewModel to observe changes in the restaurant list.
The UI dynamically updates when restaurants are added or removed.
RestaurantRepository serves as the data layer, connecting the app to the database using Android Architecture Components.

**Comment by Yui-da-carp** [comment]
Yusra, please update in RestaurantActivity  with method to return an Intent of RestaurantActivity
Thank you
